name: run-phpstan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-10.*-php-8.1-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer install

      - name: Run phpstan
        run: composer analyze
